import {mountLibrary} from '../../components/astral-library/library.js';
const $=selector=>document.querySelector(selector),floorNames=['一层 · 阅读大厅','二层 · 典藏回廊','三层 · 星图书廊'];let lib,cut=false,night=false,selected='outside';
function sync(s){const inside=s.mode==='inside';document.body.classList.toggle('inside',inside);for(let selector of ['.indoor-head','.walk','.minimap','#crosshair'])$(selector).hidden=!inside;$('#floorLabel').textContent=floorNames[s.floor];$('#mapFloor').textContent=String(s.floor+1).padStart(2,'0');$('#viewLabel').textContent=inside?'馆内自由漫步':'建筑全景';$('#instructions').textContent=inside?'拖动看四周 · WASD / 方向键移动 · 右侧楼梯上楼':'拖动环绕 · 滚轮或双指缩放';document.querySelectorAll('[data-view]').forEach(b=>{const active=b.dataset.view===selected;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))})}
try{lib=mountLibrary($('#scene'),{onStateChange:sync,frameOffset:.07,keyboard:'global'})}catch(e){$('#loading').innerHTML='<p>无法启动 3D 场景，请使用支持 WebGL 的浏览器并开启硬件加速。</p>';throw e}
function view(name){if(!['outside','entrance','reading','gallery','upper'].includes(name))throw Error('Invalid viewpoint');selected=name==='entrance'?'reading':name;if(name==='outside')lib.exterior();else lib.enter(name);sync(lib.getState());return lib.getState()}
$('#enter').onclick=()=>view('entrance');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
function cutaway(v){cut=!!v;lib.setCutaway(cut);$('#cut').classList.toggle('active',cut);$('#cut').setAttribute('aria-pressed',String(cut));$('#cut').textContent=cut?'恢复外观':'建筑剖视'}function lighting(v){night=!!v;lib.setNight(night);document.body.classList.toggle('night',night);$('#light').classList.toggle('active',night);$('#light').setAttribute('aria-pressed',String(night))}$('#cut').onclick=()=>cutaway(!cut);$('#light').onclick=()=>lighting(!night);
for(let btn of document.querySelectorAll('[data-move]')){btn.addEventListener('pointerdown',e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);lib.setMove(btn.dataset.move,true)});for(let event of ['pointerup','pointercancel','lostpointercapture'])btn.addEventListener(event,()=>lib.setMove(btn.dataset.move,false))}
const escape=e=>{if(e.code==='Escape')view('outside')};window.addEventListener('keydown',escape);const mapTimer=setInterval(()=>{const s=lib.getState();if(s.mode!=='inside')return;let x=8+(s.position[0]+18)/36*164,y=7+(s.position[2]+16)/30*134;$('#mapDot').setAttribute('cx',x);$('#mapDot').setAttribute('cy',y);$('#mapLook').setAttribute('d',`M${x} ${y}l${-Math.sin(s.yaw)*8} ${-Math.cos(s.yaw)*8}`)},160);
const lifecycle=new AbortController();if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'set_library_view',title:'切换图书馆视角',description:'进入阅读大厅或楼上回廊，返回建筑全景，并调整剖视与灯光。',inputSchema:{type:'object',properties:{view:{type:'string',enum:['outside','entrance','reading','gallery','upper']},cutaway:{type:'boolean'},night:{type:'boolean'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['view','cutaway','night'].includes(k)))throw Error('Invalid input');if(input.view!==undefined&&!['outside','entrance','reading','gallery','upper'].includes(input.view))throw Error('Invalid viewpoint');for(let k of ['cutaway','night'])if(input[k]!==undefined&&typeof input[k]!=='boolean')throw Error('Expected boolean');if(input.view)view(input.view);if(input.cutaway!==undefined)cutaway(input.cutaway);if(input.night!==undefined)lighting(input.night);return lib.getState()}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
window.addEventListener('pagehide',e=>{if(e.persisted)return;lifecycle.abort();clearInterval(mapTimer);window.removeEventListener('keydown',escape);lib.dispose()});window.addEventListener('pageshow',e=>{if(e.persisted)sync(lib.getState())});$('#loading').style.opacity=0;setTimeout(()=>$('#loading').remove(),700);
